# Generated by Django 3.1.7 on 2021-03-15 06:42

import concurrency.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(help_text='Номер телефона в формате 0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате 0000000000', regex='^[0-9]{10}$')], verbose_name='Телефон клиента'),
        ),
    ]
